### ISSUE TITLE
.config/dbman/ must exist before default file is opened for creat

### ISSUE THREAD

**Issue by Guitarbum722** [dabbertorres/dbman#1]
It would seem that the default config file can't be written unless the `/dbman` dir already exists.

For example - the first time I ran `dbman` the following was output...
`failed to create default config file: open /Users/jkmoore/.config/dbman/config.json: no such file or directory`

If I manually created the `.config/dbman` dir, all is well.
`default config file could not be found at '~/.config/dbman/config.json'; an empty config has been created with an example`

I'd be happy to tackle this if you desire.

**Comment by dabbertorres** [comment]
Oh, yeah that'd be a little important. And by all means, feel free to tackle it!

**Comment by zsgilber** [comment]
@Guitarbum722 Any progress on this?

**Comment by Guitarbum722** [comment]
@zsgilber - you should tackle this!
